# Generated by Django 2.1.7 on 2019-04-24 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('p3app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo1',
            fields=[
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('money', models.FloatField(default=100)),
                ('day', models.IntegerField(default=1)),
                ('hd', models.IntegerField(default=0)),
                ('hv', models.FloatField(default=0)),
                ('new', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='fruit',
            name='price',
            field=models.FloatField(default=10),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='userinfo1',
            name='basket',
            field=models.ManyToManyField(default=None, to='p3app.Fruit'),
        ),
    ]
